name: Test-workflow

on:
  pull_request:
    paths:
      - show_utc_date.sh
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Run
      uses: ./.github/actions/run-bash
      env:
        UTC_DATE_FORMAT: ${{secrets.SECRET_1}}

      #with:
      #  time-format: iso
      
